ALTER TABLE artist
    ADD version BIGINT;

CREATE INDEX idx_song_name ON song (name);

ALTER TABLE genre
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE album
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE artist
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE genre
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE song
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE album
    ALTER COLUMN version DROP NOT NULL;

ALTER TABLE genre
    ALTER COLUMN version DROP NOT NULL;

ALTER TABLE song
    ALTER COLUMN version DROP NOT NULL;